// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Task;

namespace Test.Task.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20210723040813_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Test.Task.Entities.MacBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Hw")
                        .HasColumnName("hw")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Model")
                        .HasColumnName("model")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TerminalMAC")
                        .HasColumnName("terminal_mac")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Vendor")
                        .HasColumnName("vendor")
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("KVANT_EF");
                });
#pragma warning restore 612, 618
        }
    }
}
